name: ğŸª² Reportar error
description: Informar de un error o regresiÃ³n en el uso. 
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Â¡Gracias por tu interÃ©s en mejorar decide!

        Antes de continuar, verifica que [no existe un reporte de error](https://github.com/us-ferferga/decide) que coincida con el tuyo.
  - type: textarea
    attributes:
      label: âœï¸ DescripciÃ³n
      description: Una descripciÃ³n clara y concisa del problema.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ğŸš¶Pasos para reproducir
      description: Explica cÃ³mo podemos reproducirlo
    validations:
      required: true
  - type: textarea
    attributes:
      label: âœ… Comportamiento esperado
      description: Una descripciÃ³n clara y concisa del comportamiento deseado.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ğŸ“ƒRegistros
      description: Si es relevante, proporciona registros (tanto del servidor como del cliente) que nos puedan servir para identificar el problema.
      render: text
  - type: textarea
    attributes:
      label: ğŸ“· Capturas de pantalla
      description: Si aplica, capturas de pantalla que ayuden a explicar el problema.
  - type: dropdown
    attributes:
      label: ğŸ–¥ï¸ Platforma del servidor
      description: Plataforma en la que estÃ¡s corriendo el backend de decide.
      options:
        - Linux
        - Windows
        - macOS
    validations:
      required: true
  - type: dropdown
    attributes:
      label: ğŸŒNavegador del cliente
      description: Navegador con el que estÃ¡s accediendo a decide.
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Otro (Por favor, especifica cuÃ¡l en la secciÃ³n "contexto adicional")
    validations:
      required: true
  - type: textarea
    attributes:
      label: âœ¨ Contexto adicional
      description: Si lo crees necesario, proporciona otra informaciÃ³n que pueda ser relevante.
      render: text
