name:  Sugerencias
description: Proponer nuevas caracter铆sticas Informar de un error o regresi贸n en el uso. 
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por tu inter茅s en mejorar decide!

        Antes de continuar, verifica que [no existe una propuesta](https://github.com/us-ferferga/decide) similar a la tuya.
  - type: textarea
    attributes:
      label: 锔 Descripci贸n
      description: Una descripci贸n clara y concisa de lo que propones.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 堵C贸mo podemos llevarla a cabo?
      description: Si se te ocurre como podemos gestionar y planificar la implementaci贸n de tu propuesta, por favor, descr铆belo aqu铆.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: З Subsistema
      description: Si conoces el(los) subsistema(s) que hay que modificar para llevar a cabo tu propuesta, selecci贸nalos aqu铆. Puedes ver [una lista](https://github.com/us-ferferga/decide/blob/master/doc/subsistemas.md)
      multiple: true
      options:
        - Autenticacion
        - Censo
        - Votaciones
        - Cabina de votaci贸n
        - Almacenamiento de votos (cifrados)
        - Recuento / MixNet
        - Postprocesado
        - Visualizaci贸n de resultados
    validations:
      required: false
